function skillsMember() {
    return [
        'JavaScript',
        'React',
        'Node.js',
        'MongoDB',
        'Express',
        'HTML',
        'CSS',
        'Sass',
        'Git',
        'GitHub',
        'Bootstrap',
        'Materialize',
        'MySQL',
        'PostgreSQL',
        'Sequelize',
        'Mongoose',
        'Handlebars',
        'jQuery',
        'Heroku',
        'Netlify',
        'Firebase',
        'Jest',
        'Mocha',
        'Chai',
        'Travis CI',
        'Cypress',
        'Python',
        'Flask',
        'Django',
        'HTML Canvas',
        'WebGL',
        'Three.js',
        'Unity',
        'C#',
        'C++',
        'Java',
        'Ruby',
        'Ruby on Rails',
        'PHP',
        'WordPress',
        'Drupal',
        'Magento',
        'Shopify',
        'Joomla',
        'Salesforce',
        'Swift',
        'Kotlin',
        'Objective-C',
        'Android',
        'iOS',
        'Flutter',
        'React Native',
        'Xamarin',
        'Cordova',
        'PhoneGap',
        'Ionic',
        'NativeScript',
        'Appcelerator',
        'Sencha',
        'jQuery Mobile',
        'Mobile Angular UI',
        'Onsen UI',
        'Framework7',
        'Intel XDK',
        'Monaca',
        'Trigger.io',
        'Tabris',
        'Corona',
        'Kendo UI',
        'Titanium',
        'Marmalade',
        'MoSync',
        'Smartface',
        'Xojo',
        'B4X',
        'Codename One',
        'RubyMotion',
        'PhoneJS',
        'AppGyver',
        'Appcelerator',
        'Sencha',
        'jQuery Mobile',
        'Mobile Angular UI',
        'Onsen UI',
        'Framework7',
        'Intel XDK',
        'Monaca',
        'Trigger.io',
        'Tabris',
        'Corona',
        'Kendo UI',
        'Titanium',
        'Marmalade',
        'MoSync',
        'Smartface',
        'Xojo',
        'B4X',
        'Codename One',
        'RubyMotion'
        ];
}